# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: area54.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='area54.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x61rea54.proto\"2\n\x0b\x45ndpointMsg\x12\x11\n\tstart_led\x18\x01 \x01(\r\x12\x10\n\x08stop_led\x18\x02 \x01(\r\"\x88\x02\n\nSegmentMsg\x12\x12\n\nstart_time\x18\x01 \x01(\r\x12\x10\n\x08\x64uration\x18\x02 \x01(\r\x12\x12\n\nkeep_alive\x18\x03 \x01(\x08\x12\x1b\n\x05\x62\x65gin\x18\x04 \x01(\x0b\x32\x0c.EndpointMsg\x12\x19\n\x03\x65nd\x18\x05 \x01(\x0b\x32\x0c.EndpointMsg\x12%\n\x08hue_type\x18\x06 \x01(\x0e\x32\x13.SegmentMsg.HueType\x12\x11\n\thue_start\x18\x07 \x01(\r\x12\x10\n\x08hue_stop\x18\x08 \x01(\r\"<\n\x07HueType\x12\x08\n\x04NONE\x10\x00\x12\n\n\x06SINGLE\x10\x01\x12\x0c\n\x08GRADIENT\x10\x02\x12\r\n\tANIMATION\x10\x03\"B\n\x11\x42rightnessStepMsg\x12\r\n\x05start\x18\x01 \x01(\r\x12\x0c\n\x04stop\x18\x02 \x01(\r\x12\x10\n\x08\x64uration\x18\x03 \x01(\r\"y\n\x0c\x41nimationMsg\x12\x0e\n\x06\x64\x65vice\x18\x01 \x03(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1d\n\x08segments\x18\x03 \x03(\x0b\x32\x0b.SegmentMsg\x12,\n\x10\x62rightness_steps\x18\x04 \x03(\x0b\x32\x12.BrightnessStepMsgb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SEGMENTMSG_HUETYPE = _descriptor.EnumDescriptor(
  name='HueType',
  full_name='SegmentMsg.HueType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SINGLE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GRADIENT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANIMATION', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=273,
  serialized_end=333,
)
_sym_db.RegisterEnumDescriptor(_SEGMENTMSG_HUETYPE)


_ENDPOINTMSG = _descriptor.Descriptor(
  name='EndpointMsg',
  full_name='EndpointMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_led', full_name='EndpointMsg.start_led', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stop_led', full_name='EndpointMsg.stop_led', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=66,
)


_SEGMENTMSG = _descriptor.Descriptor(
  name='SegmentMsg',
  full_name='SegmentMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_time', full_name='SegmentMsg.start_time', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='SegmentMsg.duration', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keep_alive', full_name='SegmentMsg.keep_alive', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='begin', full_name='SegmentMsg.begin', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='SegmentMsg.end', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hue_type', full_name='SegmentMsg.hue_type', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hue_start', full_name='SegmentMsg.hue_start', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hue_stop', full_name='SegmentMsg.hue_stop', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SEGMENTMSG_HUETYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=333,
)


_BRIGHTNESSSTEPMSG = _descriptor.Descriptor(
  name='BrightnessStepMsg',
  full_name='BrightnessStepMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='BrightnessStepMsg.start', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stop', full_name='BrightnessStepMsg.stop', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='BrightnessStepMsg.duration', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=401,
)


_ANIMATIONMSG = _descriptor.Descriptor(
  name='AnimationMsg',
  full_name='AnimationMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device', full_name='AnimationMsg.device', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='AnimationMsg.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='segments', full_name='AnimationMsg.segments', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='brightness_steps', full_name='AnimationMsg.brightness_steps', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=524,
)

_SEGMENTMSG.fields_by_name['begin'].message_type = _ENDPOINTMSG
_SEGMENTMSG.fields_by_name['end'].message_type = _ENDPOINTMSG
_SEGMENTMSG.fields_by_name['hue_type'].enum_type = _SEGMENTMSG_HUETYPE
_SEGMENTMSG_HUETYPE.containing_type = _SEGMENTMSG
_ANIMATIONMSG.fields_by_name['segments'].message_type = _SEGMENTMSG
_ANIMATIONMSG.fields_by_name['brightness_steps'].message_type = _BRIGHTNESSSTEPMSG
DESCRIPTOR.message_types_by_name['EndpointMsg'] = _ENDPOINTMSG
DESCRIPTOR.message_types_by_name['SegmentMsg'] = _SEGMENTMSG
DESCRIPTOR.message_types_by_name['BrightnessStepMsg'] = _BRIGHTNESSSTEPMSG
DESCRIPTOR.message_types_by_name['AnimationMsg'] = _ANIMATIONMSG

EndpointMsg = _reflection.GeneratedProtocolMessageType('EndpointMsg', (_message.Message,), dict(
  DESCRIPTOR = _ENDPOINTMSG,
  __module__ = 'area54_pb2'
  # @@protoc_insertion_point(class_scope:EndpointMsg)
  ))
_sym_db.RegisterMessage(EndpointMsg)

SegmentMsg = _reflection.GeneratedProtocolMessageType('SegmentMsg', (_message.Message,), dict(
  DESCRIPTOR = _SEGMENTMSG,
  __module__ = 'area54_pb2'
  # @@protoc_insertion_point(class_scope:SegmentMsg)
  ))
_sym_db.RegisterMessage(SegmentMsg)

BrightnessStepMsg = _reflection.GeneratedProtocolMessageType('BrightnessStepMsg', (_message.Message,), dict(
  DESCRIPTOR = _BRIGHTNESSSTEPMSG,
  __module__ = 'area54_pb2'
  # @@protoc_insertion_point(class_scope:BrightnessStepMsg)
  ))
_sym_db.RegisterMessage(BrightnessStepMsg)

AnimationMsg = _reflection.GeneratedProtocolMessageType('AnimationMsg', (_message.Message,), dict(
  DESCRIPTOR = _ANIMATIONMSG,
  __module__ = 'area54_pb2'
  # @@protoc_insertion_point(class_scope:AnimationMsg)
  ))
_sym_db.RegisterMessage(AnimationMsg)


# @@protoc_insertion_point(module_scope)
