/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_AREA54_PB_H_INCLUDED
#define PB_AREA54_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _SegmentMsg_HueType {
    SegmentMsg_HueType_NONE = 0,
    SegmentMsg_HueType_SINGLE = 1,
    SegmentMsg_HueType_GRADIENT = 2,
    SegmentMsg_HueType_ANIMATION = 3
} SegmentMsg_HueType;
#define _SegmentMsg_HueType_MIN SegmentMsg_HueType_NONE
#define _SegmentMsg_HueType_MAX SegmentMsg_HueType_ANIMATION
#define _SegmentMsg_HueType_ARRAYSIZE ((SegmentMsg_HueType)(SegmentMsg_HueType_ANIMATION+1))

/* Struct definitions */
typedef struct _AnimationMsg {
    pb_callback_t device;
    char name[40];
    pb_callback_t segments;
    pb_callback_t brightness_steps;
/* @@protoc_insertion_point(struct:AnimationMsg) */
} AnimationMsg;


typedef struct _BrightnessStepMsg {
    uint32_t start;
    uint32_t stop;
    uint32_t duration;
/* @@protoc_insertion_point(struct:BrightnessStepMsg) */
} BrightnessStepMsg;


typedef struct _EndpointMsg {
    uint32_t start_led;
    uint32_t stop_led;
/* @@protoc_insertion_point(struct:EndpointMsg) */
} EndpointMsg;


typedef struct _SegmentMsg {
    uint32_t start_time;
    uint32_t duration;
    bool keep_alive;
    EndpointMsg begin;
    EndpointMsg end;
    SegmentMsg_HueType hue_type;
    uint32_t hue_start;
    uint32_t hue_stop;
/* @@protoc_insertion_point(struct:SegmentMsg) */
} SegmentMsg;


/* Initializer values for message structs */
#define EndpointMsg_init_default                 {0, 0}
#define SegmentMsg_init_default                  {0, 0, 0, EndpointMsg_init_default, EndpointMsg_init_default, _SegmentMsg_HueType_MIN, 0, 0}
#define BrightnessStepMsg_init_default           {0, 0, 0}
#define AnimationMsg_init_default                {{{NULL}, NULL}, "", {{NULL}, NULL}, {{NULL}, NULL}}
#define EndpointMsg_init_zero                    {0, 0}
#define SegmentMsg_init_zero                     {0, 0, 0, EndpointMsg_init_zero, EndpointMsg_init_zero, _SegmentMsg_HueType_MIN, 0, 0}
#define BrightnessStepMsg_init_zero              {0, 0, 0}
#define AnimationMsg_init_zero                   {{{NULL}, NULL}, "", {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define AnimationMsg_device_tag                  1
#define AnimationMsg_name_tag                    2
#define AnimationMsg_segments_tag                3
#define AnimationMsg_brightness_steps_tag        4
#define BrightnessStepMsg_start_tag              1
#define BrightnessStepMsg_stop_tag               2
#define BrightnessStepMsg_duration_tag           3
#define EndpointMsg_start_led_tag                1
#define EndpointMsg_stop_led_tag                 2
#define SegmentMsg_start_time_tag                1
#define SegmentMsg_duration_tag                  2
#define SegmentMsg_keep_alive_tag                3
#define SegmentMsg_begin_tag                     4
#define SegmentMsg_end_tag                       5
#define SegmentMsg_hue_type_tag                  6
#define SegmentMsg_hue_start_tag                 7
#define SegmentMsg_hue_stop_tag                  8

/* Struct field encoding specification for nanopb */
#define EndpointMsg_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT32, start_led, 1) \
X(a, STATIC, SINGULAR, UINT32, stop_led, 2)
#define EndpointMsg_CALLBACK NULL
#define EndpointMsg_DEFAULT NULL

#define SegmentMsg_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT32, start_time, 1) \
X(a, STATIC, SINGULAR, UINT32, duration, 2) \
X(a, STATIC, SINGULAR, BOOL, keep_alive, 3) \
X(a, STATIC, SINGULAR, MESSAGE, begin, 4) \
X(a, STATIC, SINGULAR, MESSAGE, end, 5) \
X(a, STATIC, SINGULAR, UENUM, hue_type, 6) \
X(a, STATIC, SINGULAR, UINT32, hue_start, 7) \
X(a, STATIC, SINGULAR, UINT32, hue_stop, 8)
#define SegmentMsg_CALLBACK NULL
#define SegmentMsg_DEFAULT NULL
#define SegmentMsg_begin_MSGTYPE EndpointMsg
#define SegmentMsg_end_MSGTYPE EndpointMsg

#define BrightnessStepMsg_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT32, start, 1) \
X(a, STATIC, SINGULAR, UINT32, stop, 2) \
X(a, STATIC, SINGULAR, UINT32, duration, 3)
#define BrightnessStepMsg_CALLBACK NULL
#define BrightnessStepMsg_DEFAULT NULL

#define AnimationMsg_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING, device, 1) \
X(a, STATIC, SINGULAR, STRING, name, 2) \
X(a, CALLBACK, REPEATED, MESSAGE, segments, 3) \
X(a, CALLBACK, REPEATED, MESSAGE, brightness_steps, 4)
#define AnimationMsg_CALLBACK pb_default_field_callback
#define AnimationMsg_DEFAULT NULL
#define AnimationMsg_segments_MSGTYPE SegmentMsg
#define AnimationMsg_brightness_steps_MSGTYPE BrightnessStepMsg

extern const pb_msgdesc_t EndpointMsg_msg;
extern const pb_msgdesc_t SegmentMsg_msg;
extern const pb_msgdesc_t BrightnessStepMsg_msg;
extern const pb_msgdesc_t AnimationMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define EndpointMsg_fields &EndpointMsg_msg
#define SegmentMsg_fields &SegmentMsg_msg
#define BrightnessStepMsg_fields &BrightnessStepMsg_msg
#define AnimationMsg_fields &AnimationMsg_msg

/* Maximum encoded size of messages (where known) */
#define EndpointMsg_size                         12
#define SegmentMsg_size                          56
#define BrightnessStepMsg_size                   18
/* AnimationMsg_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
