/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "area54.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(EndpointMsg, EndpointMsg, AUTO)


PB_BIND(SegmentMsg, SegmentMsg, AUTO)


PB_BIND(BrightnessStepMsg, BrightnessStepMsg, AUTO)


PB_BIND(AnimationMsg, AnimationMsg, AUTO)




/* @@protoc_insertion_point(eof) */
